### ISSUE TITLE
Share button (Not working properly)

### ISSUE THREAD

**Issue by Alja7dali** [kishikawakatsumi/swift-playground#134]
Share button does work only after clicking on Settings button

<a href="https://ibb.co/whWTqXf"><img src="https://i.ibb.co/whWTqXf/Share-Button-Issue.gif" alt="Share-Button-Issue" border="0" /></a>

**Comment by kishikawakatsumi** [comment]
@Alja7dali Sorry I pushed a wrong commit. It will fix the next deployment running now.

**Comment by kishikawakatsumi** [comment]
It is now fixed. Thank you for reporting!
