### ISSUE TITLE
Support for interactive input on terminal

### ISSUE THREAD

**Issue by pakLebah** [kishikawakatsumi/swift-playground#5]
Hi, I'd like to thank you for creating this great online swift playground.

The only thing lacks from this application is an interactive terminal. It seems I can't use `readLine()` function (will produces lots of error messages). The terminal also doesn't seem to support ANSI escape sequence, so this `print("\u{1B}[93mTest")` (should print `Test` in yellow) doesn't work either.

Other than that, it's a great online swift playground. Keep up the good work! 👍 

Thank you.

**Comment by kishikawakatsumi** [comment]
The ANSI escape sequence was just supported a while ago.
I have no plan to support an interactive terminal for the time being. If you can send us a pull request, you're welcome to do so.

Thanks for the feedback!
