### ISSUE TITLE
Ability to clear output

### ISSUE THREAD

**Issue by JonnyGamer** [kishikawakatsumi/swift-playground#6]
Recently you made a change for the command line output to remember previous output history.

Personally, I appreciated it when the command line was reset per run. It would be very great if there was a toggle for this kind of option that would be saved. Or even just a button to clear it, or even a keyboard shortcut like Cmd K in Xcode. The current workaround is to refresh the page (and remember to copy the code).

**Comment by kishikawakatsumi** [comment]
Oh I see. I'll add a clear button soon. Thank you for the feedback! 👍

**Comment by kishikawakatsumi** [comment]
Fixed https://github.com/kishikawakatsumi/swift-playground/commit/dc552ff4d44ba904f9ffc5ec89b37dfa83b0e066

![image](https://user-images.githubusercontent.com/40610/97080032-69da7600-1633-11eb-913c-287e078c82df.png)

**Comment by JonnyGamer** [comment]
Thank you so much! This is great!
